#include "/Engine/Public/Platform.ush"
uint2 TextureSize;
RWTexture2D<float4> OutputTexture;

[numthreads(THREADGROUPSIZE_X, THREADGROUPSIZE_Y, THREADGROUPSIZE_Z)]
void MainCS(uint3 id : SV_DispatchThreadID)
{
	float sizeX, sizeY;
	OutputTexture.GetDimensions(sizeX, sizeY);
	if (id.x < sizeX && id.y < sizeY)
	{
		float2 uv = float2(id.x / sizeX, id.y / sizeY);
		OutputTexture[id.xy] = float4(uv, 0, 1);
	}
}